=== dpaulswamy/SOA_TRUCK_APPLICATION/Final_Project/SOA_TRUCK/XML_XSD_DTD/customers.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT customers (Customer)+>
<!ATTLIST customers
  xmlns CDATA #FIXED ''>

<!ELEMENT Customer (CustomerID,CustomerTitle,BusinessName,LocationID,
                    BillingAddress,City,State,PostalCode,Country,
                    PhoneNumber,CellNumber,OtherNumber,FaxNumber,
                    EmailAddress,CompanyName,ContactName,
                    AlternateContactName,DateEntered,CustomerType)>
<!ATTLIST Customer
  xmlns CDATA #FIXED ''>

<!ELEMENT CustomerID (#PCDATA)>
<!ATTLIST CustomerID
  xmlns CDATA #FIXED ''>

<!ELEMENT CustomerTitle (#PCDATA)>
<!ATTLIST CustomerTitle
  xmlns CDATA #FIXED ''>

<!ELEMENT BusinessName (#PCDATA)>
<!ATTLIST BusinessName
  xmlns CDATA #FIXED ''>

<!ELEMENT LocationID (#PCDATA)>
<!ATTLIST LocationID
  xmlns CDATA #FIXED ''>

<!ELEMENT BillingAddress (#PCDATA)>
<!ATTLIST BillingAddress
  xmlns CDATA #FIXED ''>

<!ELEMENT City (#PCDATA)>
<!ATTLIST City
  xmlns CDATA #FIXED ''>

<!ELEMENT State (#PCDATA)>
<!ATTLIST State
  xmlns CDATA #FIXED ''>

<!ELEMENT PostalCode (#PCDATA)>
<!ATTLIST PostalCode
  xmlns CDATA #FIXED ''>

<!ELEMENT Country (#PCDATA)>
<!ATTLIST Country
  xmlns CDATA #FIXED ''>

<!ELEMENT PhoneNumber (#PCDATA)>
<!ATTLIST PhoneNumber
  xmlns CDATA #FIXED ''>

<!ELEMENT CellNumber (#PCDATA)>
<!ATTLIST CellNumber
  xmlns CDATA #FIXED ''>

<!ELEMENT OtherNumber (#PCDATA)>
<!ATTLIST OtherNumber
  xmlns CDATA #FIXED ''>

<!ELEMENT FaxNumber (#PCDATA)>
<!ATTLIST FaxNumber
  xmlns CDATA #FIXED ''>

<!ELEMENT EmailAddress (#PCDATA)>
<!ATTLIST EmailAddress
  xmlns CDATA #FIXED ''>

<!ELEMENT CompanyName (#PCDATA)>
<!ATTLIST CompanyName
  xmlns CDATA #FIXED ''>

<!ELEMENT ContactName (#PCDATA)>
<!ATTLIST ContactName
  xmlns CDATA #FIXED ''>

<!ELEMENT AlternateContactName (#PCDATA)>
<!ATTLIST AlternateContactName
  xmlns CDATA #FIXED ''>

<!ELEMENT DateEntered (#PCDATA)>
<!ATTLIST DateEntered
  xmlns CDATA #FIXED ''>

<!ELEMENT CustomerType (#PCDATA)>
<!ATTLIST CustomerType
  xmlns CDATA #FIXED ''>

=== dpaulswamy/SOA_TRUCK_APPLICATION/Final_Project/SOA_TRUCK/XML_XSD_DTD/Customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE customer SYSTEM "customers.dtd">
<customers>
	<Customer>
		<CustomerID>C104</CustomerID>
		<CustomerTitle>Mr</CustomerTitle>
		<BusinessName>SmallBusiness</BusinessName>
		<LocationID>L101</LocationID>
		<BillingAddress>2801 South King drive apt 1815</BillingAddress>
		<City>Chicago</City>
		<State>IL</State>
		<PostalCode>60616</PostalCode>
		<Country>USA</Country>
		<PhoneNumber>3128664434</PhoneNumber>
		<CellNumber>3128664434</CellNumber>
		<OtherNumber>3128664434</OtherNumber>
		<FaxNumber>3128664434</FaxNumber>
		<EmailAddress>smallbusiness@gmail.com</EmailAddress>
		<CompanyName>BusinessBank</CompanyName>
		<ContactName>Deepak</ContactName>
		<AlternateContactName>Deepak</AlternateContactName>
		<DateEntered>2017-10-04</DateEntered>
		<CustomerType>Private</CustomerType>
	</Customer>
	<Customer>
		<CustomerID>C102</CustomerID>
		<CustomerTitle>Ms</CustomerTitle>
		<BusinessName>LocalBusiness</BusinessName>
		<LocationID>L102</LocationID>
		<BillingAddress>2951 Westmont ave apt 1109</BillingAddress>
		<City>Palo</City>
		<State>CA</State>
		<PostalCode>61612</PostalCode>
		<Country>USA</Country>
		<PhoneNumber>3125390204</PhoneNumber>
		<CellNumber>3125390204</CellNumber>
		<OtherNumber>3125390204</OtherNumber>
		<FaxNumber>3125390204</FaxNumber>
		<EmailAddress>localbusiness@gmail.com</EmailAddress>
		<CompanyName>LocalBank</CompanyName>
		<ContactName>Samata</ContactName>
		<AlternateContactName>Samata</AlternateContactName>
		<DateEntered>2017-03-27</DateEntered>
		<CustomerType>Public</CustomerType>
	</Customer>
	<Customer>
		<CustomerID>C103</CustomerID>
		<CustomerTitle>Mr</CustomerTitle>
		<BusinessName>LargeBusiness</BusinessName>
		<LocationID>L103</LocationID>
		<BillingAddress>2851 Rosemont ave apt 2015</BillingAddress>
		<City>Tampa</City>
		<State>FL</State>
		<PostalCode>62658</PostalCode>
		<Country>USA</Country>
		<PhoneNumber>3256987784</PhoneNumber>
		<CellNumber>3256987784</CellNumber>
		<OtherNumber>3256987784</OtherNumber>
		<FaxNumber>3256987784</FaxNumber>
		<EmailAddress>largebusiness@gmail.com</EmailAddress>
		<CompanyName>NationalBank</CompanyName>
		<ContactName>Sagar</ContactName>
		<AlternateContactName>Sagar</AlternateContactName>
		<DateEntered>2017-03-27</DateEntered>
		<CustomerType>Public</CustomerType>
	</Customer>
</customers>
