=== dpaulswamy/SOA_TRUCK_APPLICATION/Final_Project/SOA_TRUCK/XML_XSD_DTD/invoices.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT invoices (Invoice)+>
<!ATTLIST invoices
  xmlns CDATA #FIXED ''>

<!ELEMENT Invoice (InvoiceID,InvoiceDate,DueDate,OrderID,CustomerID,
                   OrderTotalAmount)>
<!ATTLIST Invoice
  xmlns CDATA #FIXED ''>

<!ELEMENT InvoiceID (#PCDATA)>
<!ATTLIST InvoiceID
  xmlns CDATA #FIXED ''>

<!ELEMENT InvoiceDate (#PCDATA)>
<!ATTLIST InvoiceDate
  xmlns CDATA #FIXED ''>

<!ELEMENT DueDate (#PCDATA)>
<!ATTLIST DueDate
  xmlns CDATA #FIXED ''>

<!ELEMENT OrderID (#PCDATA)>
<!ATTLIST OrderID
  xmlns CDATA #FIXED ''>

<!ELEMENT CustomerID (#PCDATA)>
<!ATTLIST CustomerID
  xmlns CDATA #FIXED ''>

<!ELEMENT OrderTotalAmount (#PCDATA)>
<!ATTLIST OrderTotalAmount
  xmlns CDATA #FIXED ''>

=== dpaulswamy/SOA_TRUCK_APPLICATION/Final_Project/SOA_TRUCK/XML_XSD_DTD/Invoice.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE invoice SYSTEM "invoices.dtd">
<invoices>
	<Invoice>
		<InvoiceID>INV101</InvoiceID>
		<InvoiceDate>2017/04/20</InvoiceDate>
		<DueDate>2017/05/20</DueDate>
		<OrderID>ORD101</OrderID>
		<CustomerID>C101</CustomerID>
		<OrderTotalAmount>1500</OrderTotalAmount>
	</Invoice>
	<Invoice>
		<InvoiceID>INV102</InvoiceID>
		<InvoiceDate>2017/06/20</InvoiceDate>
		<DueDate>2017/07/20</DueDate>
		<OrderID>ORD102</OrderID>
		<CustomerID>C102</CustomerID>
		<OrderTotalAmount>2500</OrderTotalAmount>
	</Invoice>
	<Invoice>
		<InvoiceID>INV103</InvoiceID>
		<InvoiceDate>2017/08/20</InvoiceDate>
		<DueDate>2017/09/20</DueDate>
		<OrderID>ORD103</OrderID>
		<CustomerID>C103</CustomerID>
		<OrderTotalAmount>3500</OrderTotalAmount>
	</Invoice>
</invoices>
