=== dpaulswamy/SOA_TRUCK_APPLICATION/Final_Project/SOA_TRUCK/XML_XSD_DTD/locations.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT locations (Location)+>
<!ATTLIST locations
  xmlns CDATA #FIXED ''>

<!ELEMENT Location (LocationID,locName,locationCode,isActive,CustomerID,
                    addressstreet1,addressstreet2,city,state,postalCode,
                    region,location_contact_name,locPhone,locFaxNumber,
                    locEmail)>
<!ATTLIST Location
  xmlns CDATA #FIXED ''>

<!ELEMENT LocationID (#PCDATA)>
<!ATTLIST LocationID
  xmlns CDATA #FIXED ''>

<!ELEMENT locName (#PCDATA)>
<!ATTLIST locName
  xmlns CDATA #FIXED ''>

<!ELEMENT locationCode (#PCDATA)>
<!ATTLIST locationCode
  xmlns CDATA #FIXED ''>

<!ELEMENT isActive (#PCDATA)>
<!ATTLIST isActive
  xmlns CDATA #FIXED ''>

<!ELEMENT CustomerID (#PCDATA)>
<!ATTLIST CustomerID
  xmlns CDATA #FIXED ''>

<!ELEMENT addressstreet1 (#PCDATA)>
<!ATTLIST addressstreet1
  xmlns CDATA #FIXED ''>

<!ELEMENT addressstreet2 (#PCDATA)>
<!ATTLIST addressstreet2
  xmlns CDATA #FIXED ''>

<!ELEMENT city (#PCDATA)>
<!ATTLIST city
  xmlns CDATA #FIXED ''>

<!ELEMENT state (#PCDATA)>
<!ATTLIST state
  xmlns CDATA #FIXED ''>

<!ELEMENT postalCode (#PCDATA)>
<!ATTLIST postalCode
  xmlns CDATA #FIXED ''>

<!ELEMENT region (#PCDATA)>
<!ATTLIST region
  xmlns CDATA #FIXED ''>

<!ELEMENT location_contact_name (#PCDATA)>
<!ATTLIST location_contact_name
  xmlns CDATA #FIXED ''>

<!ELEMENT locPhone (#PCDATA)>
<!ATTLIST locPhone
  xmlns CDATA #FIXED ''>

<!ELEMENT locFaxNumber (#PCDATA)>
<!ATTLIST locFaxNumber
  xmlns CDATA #FIXED ''>

<!ELEMENT locEmail (#PCDATA)>
<!ATTLIST locEmail
  xmlns CDATA #FIXED ''>

=== dpaulswamy/SOA_TRUCK_APPLICATION/Final_Project/SOA_TRUCK/XML_XSD_DTD/Location.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE location SYSTEM "locations.dtd">
<locations>
	<Location>
		<LocationID>L101</LocationID>
		<locName>kdrv</locName>
	    <locationCode>LC101</locationCode>
	    <isActive>Yes</isActive>
	    <CustomerID>C101</CustomerID>
	    <addressstreet1>Prairie</addressstreet1>
	    <addressstreet2>Shores</addressstreet2>
	    <city>Chicago</city>
	    <state>Illinois</state>
	    <postalCode>60616</postalCode>
	    <region>South</region>
	    <location_contact_name>ps</location_contact_name>
	    <locPhone>987654321</locPhone>
	    <locFaxNumber>123456789</locFaxNumber>
	    <locEmail>pshores@gmail.com</locEmail>
	</Location>
	<Location>
		<LocationID>L102</LocationID>
		<locName>Palo</locName>
	    <locationCode>LC102</locationCode>
	    <isActive>Yes</isActive>
	    <CustomerID>C102</CustomerID>
	    <addressstreet1>Westmont</addressstreet1>
	    <addressstreet2>Avenue</addressstreet2>
	    <city>Palo</city>
	    <state>California</state>
	    <postalCode>61612</postalCode>
	    <region>South</region>
	    <location_contact_name>pa</location_contact_name>
	    <locPhone>987654322</locPhone>
	    <locFaxNumber>123456788</locFaxNumber>
	    <locEmail>wavenue@gmail.com</locEmail>
	</Location>
	<Location>
		<LocationID>L103</LocationID>
		<locName>Tampa</locName>
	    <locationCode>LC103</locationCode>
	    <isActive>Yes</isActive>
	    <CustomerID>C103</CustomerID>
	    <addressstreet1>Rosemont</addressstreet1>
	    <addressstreet2>Avenue</addressstreet2>
	    <city>Tampa</city>
	    <state>Florida</state>
	    <postalCode>62658</postalCode>
	    <region>South</region>
	    <location_contact_name>ta</location_contact_name>
	    <locPhone>8896651458</locPhone>
	    <locFaxNumber>2589630147</locFaxNumber>
	    <locEmail>ravenue@gmail.com</locEmail>
	</Location>
</locations>
