=== dpaulswamy/SOA_TRUCK_APPLICATION/Final_Project/SOA_TRUCK/XML_XSD_DTD/pricings.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT pricings (Pricing)+>
<!ATTLIST pricings
  xmlns CDATA #FIXED ''>

<!ELEMENT Pricing (priceID,locationIDFrom,locationIDTo,price,
                   locationCodeFrom,locationCodeTo,locationNameFrom,
                   locationNameTo,CustomerID,type,type1)>
<!ATTLIST Pricing
  xmlns CDATA #FIXED ''>

<!ELEMENT priceID (#PCDATA)>
<!ATTLIST priceID
  xmlns CDATA #FIXED ''>

<!ELEMENT locationIDFrom (#PCDATA)>
<!ATTLIST locationIDFrom
  xmlns CDATA #FIXED ''>

<!ELEMENT locationIDTo (#PCDATA)>
<!ATTLIST locationIDTo
  xmlns CDATA #FIXED ''>

<!ELEMENT price (#PCDATA)>
<!ATTLIST price
  xmlns CDATA #FIXED ''>

<!ELEMENT locationCodeFrom (#PCDATA)>
<!ATTLIST locationCodeFrom
  xmlns CDATA #FIXED ''>

<!ELEMENT locationCodeTo (#PCDATA)>
<!ATTLIST locationCodeTo
  xmlns CDATA #FIXED ''>

<!ELEMENT locationNameFrom (#PCDATA)>
<!ATTLIST locationNameFrom
  xmlns CDATA #FIXED ''>

<!ELEMENT locationNameTo (#PCDATA)>
<!ATTLIST locationNameTo
  xmlns CDATA #FIXED ''>

<!ELEMENT CustomerID (#PCDATA)>
<!ATTLIST CustomerID
  xmlns CDATA #FIXED ''>

<!ELEMENT type (#PCDATA)>
<!ATTLIST type
  xmlns CDATA #FIXED ''>

<!ELEMENT type1 (#PCDATA)>
<!ATTLIST type1
  xmlns CDATA #FIXED ''>

=== dpaulswamy/SOA_TRUCK_APPLICATION/Final_Project/SOA_TRUCK/XML_XSD_DTD/Pricing.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pricing SYSTEM "pricings.dtd">
<pricings>
	<Pricing>
		<priceID>P101</priceID>
		<locationIDFrom>121</locationIDFrom>
		<locationIDTo>212</locationIDTo>
		<price>1111</price>
		<locationCodeFrom>2345</locationCodeFrom>
		<locationCodeTo>5432</locationCodeTo>
		<locationNameFrom>Chicago</locationNameFrom>
		<locationNameTo>Naperville</locationNameTo>
		<CustomerID>C101</CustomerID>
		<type>price1</type>
		<type1>Tx_price1</type1>
	</Pricing>
	<Pricing>
		<priceID>P102</priceID>
		<locationIDFrom>111</locationIDFrom>
		<locationIDTo>222</locationIDTo>
		<price>2111</price>
		<locationCodeFrom>3345</locationCodeFrom>
		<locationCodeTo>6432</locationCodeTo>
		<locationNameFrom>Chester</locationNameFrom>
		<locationNameTo>Aurora</locationNameTo>
		<CustomerID>C102</CustomerID>
		<type>price2</type>
		<type1>Tx_price2</type1>
	</Pricing>
	<Pricing>
		<priceID>P103</priceID>
		<locationIDFrom>221</locationIDFrom>
		<locationIDTo>312</locationIDTo>
		<price>1141</price>
		<locationCodeFrom>2347</locationCodeFrom>
		<locationCodeTo>5431</locationCodeTo>
		<locationNameFrom>Westmont</locationNameFrom>
		<locationNameTo>Chicago</locationNameTo>
		<CustomerID>C103</CustomerID>
		<type>price3</type>
		<type1>Tx_price3</type1>
	</Pricing>
</pricings>
