=== dpaulswamy/SOA_TRUCK_APPLICATION/Final_Project/SOA_TRUCK/XML_XSD_DTD/transactions.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT transaction (Transaction)+>
<!ATTLIST transaction
  xmlns CDATA #FIXED ''>

<!ELEMENT Transaction (TransactionID,OrderID,priceID,TranxDate,
                       TranxDesc,TranxAmt,Make,Model,Year,EmployeeID,
                       TruckNo,Discount,Quantity,UnitPrice,DriverPrice,
                       VIN,RunNumber,Special,Rate,Surcharge,Tx_priceID,
                       Amount,Qty,Description,Tx_date,Tx_car_make,
                       Tx_car_model,Tx_car_year,Tx_car_VIN)>
<!ATTLIST Transaction
  xmlns CDATA #FIXED ''>

<!ELEMENT TransactionID (#PCDATA)>
<!ATTLIST TransactionID
  xmlns CDATA #FIXED ''>

<!ELEMENT OrderID (#PCDATA)>
<!ATTLIST OrderID
  xmlns CDATA #FIXED ''>

<!ELEMENT priceID (#PCDATA)>
<!ATTLIST priceID
  xmlns CDATA #FIXED ''>

<!ELEMENT TranxDate (#PCDATA)>
<!ATTLIST TranxDate
  xmlns CDATA #FIXED ''>

<!ELEMENT TranxDesc (#PCDATA)>
<!ATTLIST TranxDesc
  xmlns CDATA #FIXED ''>

<!ELEMENT TranxAmt (#PCDATA)>
<!ATTLIST TranxAmt
  xmlns CDATA #FIXED ''>

<!ELEMENT Make (#PCDATA)>
<!ATTLIST Make
  xmlns CDATA #FIXED ''>

<!ELEMENT Model (#PCDATA)>
<!ATTLIST Model
  xmlns CDATA #FIXED ''>

<!ELEMENT Year (#PCDATA)>
<!ATTLIST Year
  xmlns CDATA #FIXED ''>

<!ELEMENT EmployeeID (#PCDATA)>
<!ATTLIST EmployeeID
  xmlns CDATA #FIXED ''>

<!ELEMENT TruckNo (#PCDATA)>
<!ATTLIST TruckNo
  xmlns CDATA #FIXED ''>

<!ELEMENT Discount (#PCDATA)>
<!ATTLIST Discount
  xmlns CDATA #FIXED ''>

<!ELEMENT Quantity (#PCDATA)>
<!ATTLIST Quantity
  xmlns CDATA #FIXED ''>

<!ELEMENT UnitPrice (#PCDATA)>
<!ATTLIST UnitPrice
  xmlns CDATA #FIXED ''>

<!ELEMENT DriverPrice (#PCDATA)>
<!ATTLIST DriverPrice
  xmlns CDATA #FIXED ''>

<!ELEMENT VIN (#PCDATA)>
<!ATTLIST VIN
  xmlns CDATA #FIXED ''>

<!ELEMENT RunNumber (#PCDATA)>
<!ATTLIST RunNumber
  xmlns CDATA #FIXED ''>

<!ELEMENT Special (#PCDATA)>
<!ATTLIST Special
  xmlns CDATA #FIXED ''>

<!ELEMENT Rate (#PCDATA)>
<!ATTLIST Rate
  xmlns CDATA #FIXED ''>

<!ELEMENT Surcharge (#PCDATA)>
<!ATTLIST Surcharge
  xmlns CDATA #FIXED ''>

<!ELEMENT Tx_priceID (#PCDATA)>
<!ATTLIST Tx_priceID
  xmlns CDATA #FIXED ''>

<!ELEMENT Amount (#PCDATA)>
<!ATTLIST Amount
  xmlns CDATA #FIXED ''>

<!ELEMENT Qty (#PCDATA)>
<!ATTLIST Qty
  xmlns CDATA #FIXED ''>

<!ELEMENT Description (#PCDATA)>
<!ATTLIST Description
  xmlns CDATA #FIXED ''>

<!ELEMENT Tx_date (#PCDATA)>
<!ATTLIST Tx_date
  xmlns CDATA #FIXED ''>

<!ELEMENT Tx_car_make (#PCDATA)>
<!ATTLIST Tx_car_make
  xmlns CDATA #FIXED ''>

<!ELEMENT Tx_car_model (#PCDATA)>
<!ATTLIST Tx_car_model
  xmlns CDATA #FIXED ''>

<!ELEMENT Tx_car_year (#PCDATA)>
<!ATTLIST Tx_car_year
  xmlns CDATA #FIXED ''>

<!ELEMENT Tx_car_VIN (#PCDATA)>
<!ATTLIST Tx_car_VIN
  xmlns CDATA #FIXED ''>

=== dpaulswamy/SOA_TRUCK_APPLICATION/Final_Project/SOA_TRUCK/XML_XSD_DTD/Transaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE transaction SYSTEM "transactions.dtd">
<transaction>
	<Transaction>
		<TransactionID>TRNX101</TransactionID>
		<OrderID>ORD101</OrderID>
		<priceID>P101</priceID>
		<TranxDate>2017/02/15</TranxDate>
		<TranxDesc>Mark Trucks</TranxDesc>
		<TranxAmt>55000</TranxAmt>
		<Make>Mark</Make>
		<Model>HeavyDuty</Model>
		<Year>2017</Year>
		<EmployeeID>EP101</EmployeeID>
		<TruckNo>R2614 Wisconsin 76</TruckNo>
		<Discount>1500</Discount>
		<Quantity>2</Quantity>
		<UnitPrice>35000</UnitPrice>
		<DriverPrice>1500</DriverPrice>
		<VIN>1HGCM82633A004352</VIN>
		<RunNumber>1572 10760USA H123AB</RunNumber>
		<Special>1200</Special>
		<Rate>12</Rate>
		<Surcharge>10</Surcharge>
		<Tx_priceID>TRNXP101</Tx_priceID>
		<Amount>50000</Amount>
		<Qty>2</Qty>
		<Description>Mark Trucks</Description>
		<Tx_date>2017/02/15</Tx_date>
		<Tx_car_make>Mark</Tx_car_make>
		<Tx_car_model>HeavyDuty</Tx_car_model>
		<Tx_car_year>2017</Tx_car_year>
		<Tx_car_VIN>1HGCM82633A004352</Tx_car_VIN>
	</Transaction>
	<Transaction>
		<TransactionID>TRNX102</TransactionID>
		<OrderID>ORD102</OrderID>
		<priceID>P102</priceID>
		<TranxDate>2017/02/16</TranxDate>
		<TranxDesc>Belmont Trucks</TranxDesc>
		<TranxAmt>65000</TranxAmt>
		<Make>Belmont</Make>
		<Model>Rover</Model>
		<Year>2018</Year>
		<EmployeeID>EP102</EmployeeID>
		<TruckNo>R2615 Wisconsin 76</TruckNo>
		<Discount>2500</Discount>
		<Quantity>4</Quantity>
		<UnitPrice>38000</UnitPrice>
		<DriverPrice>1600</DriverPrice>
		<VIN>1HGCM82633A004354</VIN>
		<RunNumber>1571 10760USA H123AC</RunNumber>
		<Special>1000</Special>
		<Rate>13</Rate>
		<Surcharge>12</Surcharge>
		<Tx_priceID>TRNXP102</Tx_priceID>
		<Amount>90000</Amount>
		<Qty>4</Qty>
		<Description>Belmont Trucks</Description>
		<Tx_date>2017/02/15</Tx_date>
		<Tx_car_make>Belmont</Tx_car_make>
		<Tx_car_model>Rover</Tx_car_model>
		<Tx_car_year>2018</Tx_car_year>
		<Tx_car_VIN>1HGCM82633A004354</Tx_car_VIN>
	</Transaction>
	<Transaction>
		<TransactionID>TRNX103</TransactionID>
		<OrderID>ORD103</OrderID>
		<priceID>P103</priceID>
		<TranxDate>2017/02/17</TranxDate>
		<TranxDesc>Grey Trucks</TranxDesc>
		<TranxAmt>45000</TranxAmt>
		<Make>Gery</Make>
		<Model>Tuxedo</Model>
		<Year>2016</Year>
		<EmployeeID>EP103</EmployeeID>
		<TruckNo>R2617A Wisconsin 79</TruckNo>
		<Discount>3500</Discount>
		<Quantity>7</Quantity>
		<UnitPrice>8000</UnitPrice>
		<DriverPrice>600</DriverPrice>
		<VIN>1HGCM82633A004375</VIN>
		<RunNumber>1625 10800USA H123UG</RunNumber>
		<Special>2000</Special>
		<Rate>18</Rate>
		<Surcharge>11</Surcharge>
		<Tx_priceID>TRNXP103</Tx_priceID>
		<Amount>10000</Amount>
		<Qty>7</Qty>
		<Description>Grey Trucks</Description>
		<Tx_date>2017/02/17</Tx_date>
		<Tx_car_make>Grey</Tx_car_make>
		<Tx_car_model>Tuxedo</Tx_car_model>
		<Tx_car_year>2016</Tx_car_year>
		<Tx_car_VIN>1HGCM82633A004375</Tx_car_VIN>
	</Transaction>
</transaction>
