=== dpaulswamy/SOA_TRUCK_APPLICATION/Final_Project/SOA_TRUCK/XML_XSD_DTD/trucks.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT truck (Truck)+>
<!ATTLIST truck
  xmlns CDATA #FIXED ''>

<!ELEMENT Truck (TruckID,Make,Year,Model,LicensePlateNo,EmployeeID,
                 Color,VIN)>
<!ATTLIST Truck
  xmlns CDATA #FIXED ''>

<!ELEMENT TruckID (#PCDATA)>
<!ATTLIST TruckID
  xmlns CDATA #FIXED ''>

<!ELEMENT Make (#PCDATA)>
<!ATTLIST Make
  xmlns CDATA #FIXED ''>

<!ELEMENT Year (#PCDATA)>
<!ATTLIST Year
  xmlns CDATA #FIXED ''>

<!ELEMENT Model (#PCDATA)>
<!ATTLIST Model
  xmlns CDATA #FIXED ''>

<!ELEMENT LicensePlateNo (#PCDATA)>
<!ATTLIST LicensePlateNo
  xmlns CDATA #FIXED ''>

<!ELEMENT EmployeeID (#PCDATA)>
<!ATTLIST EmployeeID
  xmlns CDATA #FIXED ''>

<!ELEMENT Color (#PCDATA)>
<!ATTLIST Color
  xmlns CDATA #FIXED ''>

<!ELEMENT VIN (#PCDATA)>
<!ATTLIST VIN
  xmlns CDATA #FIXED ''>

=== dpaulswamy/SOA_TRUCK_APPLICATION/Final_Project/SOA_TRUCK/XML_XSD_DTD/Trucks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE truck SYSTEM "trucks.dtd">
<truck>
	<Truck>
	<TruckID>T101</TruckID>
		<Make>Force</Make>
		<Year>1991</Year>
		<Model>Model S</Model>
		<LicensePlateNo>LPN101</LicensePlateNo>
		<EmployeeID>EP101</EmployeeID>
		<Color>Grey</Color>
		<VIN>1A2U332D092E55V101</VIN>
	</Truck>
	<Truck>
		<TruckID>T102</TruckID>
		<Make>Tata</Make>
		<Year>2002</Year>
		<Model>Model T</Model>
		<LicensePlateNo>LPN102</LicensePlateNo>
		<EmployeeID>EP102</EmployeeID>
		<Color>Black</Color>
		<VIN>1A2U332D092E55V102</VIN>
	</Truck>
	<Truck>
		<TruckID>T103</TruckID>
		<Make>AsokaLeyland</Make>
		<Year>2006</Year>
		<Model>Model U</Model>
		<LicensePlateNo>LPN103</LicensePlateNo>
		<EmployeeID>EP103</EmployeeID>
		<Color>Red</Color>
		<VIN>1A2U332D092E55V103</VIN>
	</Truck>
</truck>
